version: '3.8'
services:
  app:
    build: .
    container_name: ai-procurement
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped 